### ISSUE TITLE
Error in Preprocess

### ISSUE THREAD

**Issue by wanglu0609** [Rayhane-mamah/Tacotron-2#105]
I tried to run preprocess.py and get this error:

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/wanglu/Tacotron-2/datasets/preprocessor.py", line 104, in _process_utterance
    mel_spectrogram = audio.melspectrogram(wav, hparams).astype(np.float32)
  File "/home/wanglu/Tacotron-2/datasets/audio.py", line 55, in melspectrogram
    D = _stft(wav, hparams)
  File "/home/wanglu/Tacotron-2/datasets/audio.py", line 115, in _stft
    return _lws_processor(hparams).stft(y).T
  File "/home/wanglu/Tacotron-2/datasets/audio.py", line 99, in _lws_processor
    return lws.lws(hparams.n_fft, get_hop_size(hparams), fftsize=hparams.win_size, mode="speech")
  File "lws.pyx", line 338, in lws.lws.__init__ (lws.bycython.cpp:14774)
TypeError: __init__() got an unexpected keyword argument 'fftsize'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 109, in <module>
    main()
  File "preprocess.py", line 105, in main
    run_preprocess(args, modified_hp)
  File "preprocess.py", line 82, in run_preprocess
    preprocess(args, input_folders, output_folder, hparams)
  File "preprocess.py", line 16, in preprocess
    metadata = preprocessor.build_from_path(hparams, input_folders, mel_dir, linear_dir, wav_dir, args.n_jobs, tqdm=tqdm)
  File "/home/wanglu/Tacotron-2/datasets/preprocessor.py", line 40, in build_from_path
    return [future.result() for future in tqdm(futures) if future.result() is not None]
  File "/home/wanglu/Tacotron-2/datasets/preprocessor.py", line 40, in <listcomp>
    return [future.result() for future in tqdm(futures) if future.result() is not None]
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
TypeError: __init__() got an unexpected keyword argument 'fftsize'

Could someone help me with this?

**Comment by ddemilla** [comment]
I have the same error.

**Comment by ddemilla** [comment]
You can fix this issue by removing the "fftsize" parameter in the lws function call in audio.py. 
Change line 99 to:
```
return lws.lws(hparams.n_fft, get_hop_size(hparams),  mode="speech")
```
I'm not sure what that parameter is supposed to be though.
