### ISSUE TITLE
About problems of  test WaveNet model 

### ISSUE THREAD

**Issue by v-yunbin** [Rayhane-mamah/Tacotron-2#106]
_1. When I test the test WaveNet model on 7.6k, no wave files have been synthesized. And just echo follows:_
    **1)** commad: python synthesize.py --model='WaveNet'
 
![errors](https://user-images.githubusercontent.com/38179632/43054463-4b58a336-8e64-11e8-9612-40e8330ec1c2.png)

  **2)** command: python synthesize.py --model='Both'

  Constructing model: WaveNet
Initializing Wavenet model.  Dimensions (? = dynamic shape): 
  Train mode:                False
  Eval mode:                 False
  Synthesis mode:            True
  local_condition:            (1, 80, ?)
  outputs:                    (?,)
Loading checkpoint: logs-Tacotron-2/wave_pretrained/wavenet_model.ckpt-76000
Traceback (most recent call last):
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAverage not found in checkpoint
	 [[Node: model_1/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model_1/save/Const_0_0, model_1/save/RestoreV2/tensor_names, model_1/save/RestoreV2/shape_and_slices)]]
	 [[Node: model_1/save/RestoreV2/_493 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_498_model_1/save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesize.py", line 91, in <module>
    main()
  File "synthesize.py", line 85, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 34, in synthesize
    wavenet_synthesize(args, hparams, wave_checkpoint)
  File "/data02/zhangyb/test1/Tacotron-2/wavenet_vocoder/synthesize.py", line 78, in wavenet_synthesize
    run_synthesis(args, checkpoint_path, output_dir, hparams)
  File "/data02/zhangyb/test1/Tacotron-2/wavenet_vocoder/synthesize.py", line 19, in run_synthesis
    synth.load(checkpoint_path, hparams)
  File "/data02/zhangyb/test1/Tacotron-2/wavenet_vocoder/synthesizer.py", line 32, in load
    load_averaged_model(self.session, sh_saver, checkpoint_path)
  File "/data02/zhangyb/test1/Tacotron-2/wavenet_vocoder/train.py", line 56, in load_averaged_model
    sh_saver.restore(sess, checkpoint_path)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAverage not found in checkpoint
	 [[Node: model_1/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model_1/save/Const_0_0, model_1/save/RestoreV2/tensor_names, model_1/save/RestoreV2/shape_and_slices)]]
	 [[Node: model_1/save/RestoreV2/_493 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_498_model_1/save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'model_1/save/RestoreV2', defined at:
  File "synthesize.py", line 91, in <module>
    main()
  File "synthesize.py", line 85, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 34, in synthesize
    wavenet_synthesize(args, hparams, wave_checkpoint)
  File "/data02/zhangyb/test1/Tacotron-2/wavenet_vocoder/synthesize.py", line 78, in wavenet_synthesize
    run_synthesis(args, checkpoint_path, output_dir, hparams)
  File "/data02/zhangyb/test1/Tacotron-2/wavenet_vocoder/synthesize.py", line 19, in run_synthesis
    synth.load(checkpoint_path, hparams)
  File "/data02/zhangyb/test1/Tacotron-2/wavenet_vocoder/synthesizer.py", line 27, in load
    sh_saver = create_shadow_saver(self.model)
  File "/data02/zhangyb/test1/Tacotron-2/wavenet_vocoder/train.py", line 53, in create_shadow_saver
    return tf.train.Saver(shadow_dict, max_to_keep=5)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 472, in _AddRestoreOps
    restore_sequentially)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 886, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAverage not found in checkpoint
	 [[Node: model_1/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model_1/save/Const_0_0, model_1/save/RestoreV2/tensor_names, model_1/save/RestoreV2/shape_and_slices)]]
	 [[Node: model_1/save/RestoreV2/_493 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_498_model_1/save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

_2. But the predict is normal in train stage:_
![step-76000-waveplot](https://user-images.githubusercontent.com/38179632/43054410-fcfd6b2c-8e63-11e8-8464-c22ab4269752.png)

**Comment by dsilva-tbox** [comment]
Same here

**Comment by v-yunbin** [comment]
I have donwload latest codes and do follows as author said: train with "Tacotron2" and test with "Both", still stuck in the problem.
@Rayhane-mamah, dou you have some suggestion?

**Comment by Yeongtae** [comment]
check #https://github.com/Rayhane-mamah/Tacotron-2/issues/64

This is my implementation.
[tacotron_bugfix.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2222950/tacotron_bugfix.zip)
I had edited codes in 'hparam.py', '/wavenet_vocoder/train.py', and '/wavenet_vocoder/synthesize.py' using hard coding.
It will be added to pull request soon.

**Comment by v-yunbin** [comment]
@Yeongtae thank for your efforts for fixing bug, I would try it

**Comment by dsilva-tbox** [comment]
@Yeongtae , does your synthesis reads the sentences from the hparams.py? 

Also, @v-yunbin, I have run the code and you just need to wait a bit. It takes some computational power to synthesise from wavenet. After 1 one hour I managed to synthesise 10 audio files. However, @Yeongtae , it is just noise...

![screen shot 2018-07-24 at 14 08 22](https://user-images.githubusercontent.com/37179504/43140283-87e956e6-8f4b-11e8-85d1-dcd25e520ce6.png)

**Comment by Yeongtae** [comment]
@v-yunbin It isn't stuck, it's just slow inferencing.

@dsilva-tbox because we don't converge our model and there are some bugs in wavenet_vocoder. I'm trying to fix it.

**Comment by v-yunbin** [comment]
@Yeongtae Beyond my imagination, it's so slow...  Look forward to the fix.
@dsilva-tbox we only wait to fix it.

**Comment by Yeongtae** [comment]
#https://github.com/Rayhane-mamah/Tacotron-2/pull/110

**Comment by NewEricWang** [comment]
@Yeongtae, Must we re-train wavenet model after applying your fixed code?

**Comment by Yeongtae** [comment]
@NewEricWang I just fix a bug in synthesize.py.
