### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by hiroto911** [Rayhane-mamah/Tacotron-2#123]
Hello.
I am glad that activities were resumed again this week.
By the way, the following error occurred when we started learning newly with the latest commit. I think that the commit where hparams.py changed was `num_iters = 513 -> 1025`, so it seems to be related, what do you think?

```bash
Generated 32 train batches of size 32 in 83.416 sec
Exception in thread background:
Traceback (most recent call last):
  File "/<bin>/python/3.6.5/gnu/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/<bin>/python/3.6.5/gnu/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/<home>/Tacotron-2/tacotron/feeder.py", line 162, in _enqueue_next_train_group
    self._session.run(self._enqueue_op, feed_dict=feed_dict)
  File "/<home>/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/<home>/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 698, 513) for Tensor 'datafeeder/linear_targets:0', which has shape '(?, ?, 1025)'


Generated 48 test batches of size 32 in 122.061 sec
Exception in thread background:
Traceback (most recent call last):
  File "/<bin>/python/3.6.5/gnu/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/<bin>/python/3.6.5/gnu/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/<home>/Tacotron-2/tacotron/feeder.py", line 170, in _enqueue_next_test_group
    self._session.run(self._eval_enqueue_op, feed_dict=feed_dict)
  File "/<home>/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/<home>/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 590, 513) for Tensor 'datafeeder/linear_targets:0', which has shape '(?, ?, 1025)'
```

**Comment by gsoul** [comment]
same issue here

**Comment by Rayhane-mamah** [comment]
Hello @hiroto911 thanks for reaching out.

I am assuming you have preprocessed your data with a different hparams.py than the one existent now. This your linears are 513-dimensional. No problem, under hparams.py you will need to modify your hparams back to what suits your data best (or do preprocessing again if your data is 24kHz).

The following parameters are what you're interested in:
https://github.com/Rayhane-mamah/Tacotron-2/blob/7cf1cf543832b7bef684dbbf176ac8b3fcaceaa1/hparams.py#L18

https://github.com/Rayhane-mamah/Tacotron-2/blob/7cf1cf543832b7bef684dbbf176ac8b3fcaceaa1/hparams.py#L31-L36

Make sure to adapt those to your data.

You can check our [old hparams](https://github.com/Rayhane-mamah/Tacotron-2/blob/08bf8e2d60925b1cd47ca69e2bb1a9447fd13b62/hparams.py) for reference about what has been changed between those lines, might help you with your case.
Tell me if the problem still persists after that :)

**Comment by hiroto911** [comment]
Hello @Rayhane-mamah thank you for your reply!
Certainly I was using old training_data. I would like to redo from preprocess again! 👍
