### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by maxguru** [Rayhane-mamah/Tacotron-2#14]
I am having difficulties running this code.  I am on Linux.

The preprocess step seemed to have completed but with some issues,
```
$ python preprocess.py --dataset='M-AILABS' --language='en_US' --voice='female' --reader='mary_ann' --merge_books=False --book='northandsouth'
WARNING:tensorflow:From /home/al/.local/lib64/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
initializing preprocessing..
Selecting data folders..
Traceback (most recent call last):
  File "preprocess.py", line 99, in <module>
    main()
  File "preprocess.py", line 95, in main
    run_preprocess(args)
  File "preprocess.py", line 78, in run_preprocess
    preprocess(args, input_folders, output_folder)
  File "preprocess.py", line 14, in preprocess
    metadata = preprocessor.build_from_path(input_folders, mel_dir, wav_dir, args.n_jobs, tqdm=tqdm)
  File "/home/al/Downloads/tacotron/Rayhane-mamah/Tacotron-2/datasets/preprocessor.py", line 31, in build_from_path
    with open(os.path.join(input_dir, 'metadata.csv'), encoding='utf-8') as f:
NotADirectoryError: [Errno 20] Not a directory: 'en_US/by_book/female/mary_ann/._.DS_Store/metadata.csv'
file en_US/by_book/female/mary_ann/midnight_passenger/wavs/midnight_passenger_05_f000269.wav present in csv metadata is not present in wav folder. skipping!
file en_US/by_book/female/mary_ann/northandsouth/wavs/northandsouth_40_f000069.wav present in csv metadata is not present in wav folder. skipping!
```
`._.DS_Store` is a file, so, i am not sure whats going on here.

The train step failed to find `training_data/train.txt` which doesn't actually exist,
```
$ python train.py --model='Tacotron'
WARNING:tensorflow:From /home/al/.local/lib64/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Checkpoint path: logs-Tacotron/pretrained/model.ckpt
Loading training data from: training_data/train.txt
Using model: Tacotron
Hyperparameters:
  allow_clipping_in_normalization: True
  attention_dim: 128
  attention_filters: 32
  attention_kernel: (31,)
  cleaners: english_cleaners
  decoder_layers: 2
  decoder_lstm_units: 1024
  embedding_dim: 512
  enc_conv_channels: 512
  enc_conv_kernel_size: (5,)
  enc_conv_num_layers: 3
  encoder_lstm_units: 256
  fft_size: 1024
  fmax: 7600
  fmin: 125
  frame_shift_ms: None
  griffin_lim_iters: 60
  hop_size: 256
  impute_finished: False
  input_type: mulaw-quantize
  log_scale_min: -32.23619130191664
  mask_encoder: False
  mask_finished: False
  max_abs_value: 4.0
  max_iters: 1000
  mel_normalization: True
  min_level_db: -100
  num_mels: 80
  outputs_per_step: 5
  postnet_channels: 512
  postnet_kernel_size: (5,)
  postnet_num_layers: 5
  power: 1.55
  prenet_layers: [256, 256]
  quantize_channels: 256
  ref_level_db: 20
  rescale: True
  rescaling_max: 0.999
  sample_rate: 22050
  silence_threshold: 2
  smoothing: False
  stop_at_any: True
  symmetric_mels: True
  tacotron_adam_beta1: 0.9
  tacotron_adam_beta2: 0.999
  tacotron_adam_epsilon: 1e-06
  tacotron_batch_size: 32
  tacotron_decay_learning_rate: True
  tacotron_decay_rate: 0.4
  tacotron_decay_steps: 50000
  tacotron_dropout_rate: 0.5
  tacotron_final_learning_rate: 1e-05
  tacotron_initial_learning_rate: 0.001
  tacotron_reg_weight: 1e-06
  tacotron_teacher_forcing_ratio: 1.0
  tacotron_zoneout_rate: 0.1
  trim_silence: True
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    main()
  File "train.py", line 26, in main
    tacotron_train(args)
  File "/home/al/Downloads/tacotron/Rayhane-mamah/Tacotron-2/tacotron/train.py", line 174, in tacotron_train
    train(log_dir, args)
  File "/home/al/Downloads/tacotron/Rayhane-mamah/Tacotron-2/tacotron/train.py", line 55, in train
    feeder = Feeder(coord, input_path, hparams)
  File "/home/al/Downloads/tacotron/Rayhane-mamah/Tacotron-2/tacotron/feeder.py", line 38, in __init__
    with open(metadata_filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'training_data/train.txt'
```
Looks like preprocess script didn't create it for some reason.

**Comment by Rayhane-mamah** [comment]
Hello Alex thanks for reporting this.

The preprocessing didn't create the train.txt because it crashed without
finishing the preprocessing.

I think I know how to solve this, I'll take care of it in a second.

Thank you for your patience.

**Comment by maxguru** [comment]
It seems like it didn't crash.  It was working for a few minutes and exited without a stack trace.

**Comment by Rayhane-mamah** [comment]
This issue should be stored now, after this commit (0330bd0161e4530acbb7bc2db00a1db95b2dc107)

If you encounter any further problems, please keep me informed.

by the way: Warnings about missing files are "okay". It is due to missing files in the actual version of the dataset and should be taken care of very soon, missing 4 or 5 files from 13000 is fine. So training will work correctly after that.

You can refer to the [README](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/README.md) for further instruction on options to choose the dataset.

**Comment by Rayhane-mamah** [comment]
I was wondering where these hidden folders were coming from :)

I'm glad to know that it's all good now, thanks for your great work @imdatsolak!

@maxguru, you tell us if there are any problems left.
