### ISSUE TITLE
Test 'python synthesize.py', get NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor:

### ISSUE THREAD

**Issue by Yeongtae** [Rayhane-mamah/Tacotron-2#141]
Loading checkpoint: logs-Tacotron-2/wave_pretrained/wavenet_model.ckpt-110000
Traceback (most recent call last):
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for logs-Tacotron-2/wave_pretrained/wavenet_model.ckpt-110000
         [[Node: model_1/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model_1/save/Const_0_0, model_1/save/RestoreV2/tensor_names, model_1/save/RestoreV2/shape_and_slices)]]
         [[Node: model_1/save/RestoreV2/_531 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_536_model_1/save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesize.py", line 92, in <module>
    main()
  File "synthesize.py", line 86, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 35, in synthesize
    wavenet_synthesize(args, hparams, wave_checkpoint)
  File "/home/hwak1234/projects/Tacotron-2/wavenet_vocoder/synthesize.py", line 75, in wavenet_synthesize
    run_synthesis(args, checkpoint_path, output_dir, hparams)
  File "/home/hwak1234/projects/Tacotron-2/wavenet_vocoder/synthesize.py", line 19, in run_synthesis
    synth.load(checkpoint_path, hparams)
  File "/home/hwak1234/projects/Tacotron-2/wavenet_vocoder/synthesizer.py", line 34, in load
    load_averaged_model(self.session, sh_saver, checkpoint_path)
  File "/home/hwak1234/projects/Tacotron-2/wavenet_vocoder/train.py", line 62, in load_averaged_model
    sh_saver.restore(sess, checkpoint_path)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for logs-Tacotron-2/wave_pretrained/wavenet_model.ckpt-110000
         [[Node: model_1/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model_1/save/Const_0_0, model_1/save/RestoreV2/tensor_names, model_1/save/RestoreV2/shape_and_slices)]]
         [[Node: model_1/save/RestoreV2/_531 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_536_model_1/save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Caused by op 'model_1/save/RestoreV2', defined at:**
  File "synthesize.py", line 92, in <module>
    main()
  File "synthesize.py", line 86, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 35, in synthesize
    wavenet_synthesize(args, hparams, wave_checkpoint)
  File "/home/hwak1234/projects/Tacotron-2/wavenet_vocoder/synthesize.py", line 75, in wavenet_synthesize
    run_synthesis(args, checkpoint_path, output_dir, hparams)
  File "/home/hwak1234/projects/Tacotron-2/wavenet_vocoder/synthesize.py", line 19, in run_synthesis
    synth.load(checkpoint_path, hparams)
  File "/home/hwak1234/projects/Tacotron-2/wavenet_vocoder/synthesizer.py", line 29, in load
    sh_saver = create_shadow_saver(self.model)
  File "/home/hwak1234/projects/Tacotron-2/wavenet_vocoder/train.py", line 59, **in create_shadow_saver
    return tf.train.Saver(shadow_dict, max_to_keep=5)**
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1311, in __init__
    self.build()
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 809, in _build_internal
    restore_sequentially, reshape)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 448, in _AddRestoreOps
    restore_sequentially)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 860, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1458, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/hwak1234/miniconda3/envs/tacotron2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for logs-Tacotron-2/wave_pretrained/wavenet_model.ckpt-110000
         [[Node: model_1/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model_1/save/Const_0_0, model_1/save/RestoreV2/tensor_names, model_1/save/RestoreV2/shape_and_slices)]]
         [[Node: model_1/save/RestoreV2/_531 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_536_model_1/save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

In my opinion, there is an error at create_shadow_saver in Tacotron-2/wavenet_vocoder/train.py
**I'm trying to dug it.**

**Comment by Yeongtae** [comment]
I have fixed it all. 
I will commit within 2 days.

**Comment by Yeongtae** [comment]
#143

**Comment by Yeongtae** [comment]
#144

**Comment by Yeongtae** [comment]
#145

**Comment by Rayhane-mamah** [comment]
I have applied easier fixes and pushed the commit, please let me know if it persists with latest changes (if you try it)
