### ISSUE TITLE
Train the WaveNet model and it occurs error after using the update code 

### ISSUE THREAD

**Issue by juihsuanlee** [Rayhane-mamah/Tacotron-2#176]
I have trained the three models before author updated it's code. Now I update the code, but when I try to run the "python train.py --model= 'WaveNet' " for more steps then it occurs error.

Here is the error  message.
![s_8481043035300](https://user-images.githubusercontent.com/26132337/44642588-73d69f00-a9ff-11e8-981e-f8ea44925f35.jpg)

**Comment by Yeongtae** [comment]
https://github.com/Rayhane-mamah/Tacotron-2/pull/137

**Comment by al3chen** [comment]
I have same issue
log is 



Generated 578 test batches of size 1 in 0.618 sec
Exception in thread background:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alchen/TA2/Tacotron-2/wavenet_vocoder/feeder.py", line 225, in _enqueue_next_test_group
    feed_dict = dict(zip(self._placeholders, self._prepare_batch(batch)))
  File "/home/alchen/TA2/Tacotron-2/wavenet_vocoder/feeder.py", line 268, in _prepare_batch
    batch = self._adjust_time_resolution(batch, self.local_condition, max_time_steps)
  File "/home/alchen/TA2/Tacotron-2/wavenet_vocoder/feeder.py", line 359, in _adjust_time_resolution
    self._assert_ready_for_upsample(x, c)
  File "/home/alchen/TA2/Tacotron-2/wavenet_vocoder/feeder.py", line 384, in _assert_ready_for_upsample
    assert len(x) % len(c) == 0 and len(x) // len(c) == audio.get_hop_size(self._hparams)
AssertionError

**Comment by cliuxinxin** [comment]
I had the same issue. Use the synthesis data to train wavenet(GTA mode).And I didn't solve it .Even use the #137 . So I just run the wavenet_preprocess.py and change the GTA = False in Hparams.... But I think I still have to fix it.
