### ISSUE TITLE
Freezing for inference / synthesis

### ISSUE THREAD

**Issue by splitice** [Rayhane-mamah/Tacotron-2#205]
Has anyone had any luck freezing the graph for synthesis?

I see @ruiboshi has started on this. @ruiboshi any luck?

**Comment by ruiboshi** [comment]
Hi @splitice, been busy with other stuff in the last couple weeks so haven't had any chance to put more effort in this again. Will update more once I have something.

**Comment by ruiboshi** [comment]
Tried freezing the wavenet graph (intialised from the Synthesizer class) with optimize_for_inference_lib but had some issues when loading it up. Don't have the details regarding this issue by hand at the moment. 

Then I tried the standard freeze_graph.py by loading a graph def and a checkpoint, the output node is specified to be _model/inference/Reshape_1_ as the actual output op _y_hat_ has a `inv_mulaw_quantize` following the reshape op implemented outside of the graph (due to softmax output) and I thought it might be better avoiding it. 

Unfortunately I'm now seeing another issue when running: 
`freeze_graph --input_graph graphs/wavenet_graph_def.pb --input_checkpoint wave_pretrained_softmax/wavenet_model.ckpt-690000 --output_graph=frozen_wavenet.pb --output_node_names='model/inference/Reshape_1' --input_binary=True`: 

> Traceback (most recent call last):
  File "/home/ruiboshi/.pyenv/tensorflow/bin/freeze_graph", line 11, in <module>
    sys.exit(run_main())
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 379, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 378, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 272, in main
    flags.saved_model_tags, checkpoint_version)
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 254, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/tools/freeze_graph.py", line 128, in freeze_graph_with_def_protos
    var_list=var_list, write_version=checkpoint_version)
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ruiboshi/.pyenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1318, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

Not sure why this is happening.. BTW, I have tf 1.10.

**Comment by splitice** [comment]
How about for the Tacotron graph? Same errors?

**Comment by ruiboshi** [comment]
The command above is for freezing the graph, referring to [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py).

The Tacotron part is quite straightforward, in my forked repo there should be a freeze.py which should do the job you're looking for, at least for the tacotron bit.

**Comment by splitice** [comment]
Could you help me out with a python example for executing that frozen graph? I've been getting a type error (I think its to do with the dynamic length of the input).

**Comment by ruiboshi** [comment]
@splitice I've managed to get both graphs frozen and running for synthesis. Checkout my fork https://github.com/ruiboshi/Tacotron-2 for more details. 

One thing to bear in mind is that you'll want to make sure your hparams are set to the same when freezing the graph from a checkpoint that was potentially trained somewhere else. 

Also, extra care might need to be taken for pre/post-processing the wavs and mels that were originally done outside of the graph (follow _wavenet_vocoder/models/wavenet.py_ and _tacotron/models/tacotron.py_).

@Rayhane-mamah  FYI, not sure if this something you'd want to merge into the main branch.

**Comment by splitice** [comment]
That looks amazing man. So much better than my attempt. I'll take a look tomorrow.

**Comment by Clouxie** [comment]
ruiboshi , may I ask you for a contact ? I would realy use your help with graph freeze. I'm also getting errors like : op type ": FIFOQueueV2 " incompatible or some errors with PyFunc :(    
text me please . "holoxe@gmail.com"

**Comment by vinayonchip** [comment]
Hi all...!
Getting the same issue. I am unable to freeze the graphs. Please help me with this.

Thanks in advance..!

**Comment by manuel3265** [comment]
@Clouxie  Could you solve the Pyfunc error?
