### ISSUE TITLE
Getting Syntax error while Training

### ISSUE THREAD

**Issue by nomitjangid** [Rayhane-mamah/Tacotron-2#228]
Hi,

I was running this on the LJSpeech-1.1 dataset,  preprocessing part ran smoothly. (with default hparams).
while training I'm getting this error

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from tacotron.synthesize import tacotron_synthesize
  File "/mnt/Tacotron-2/tacotron/synthesize.py", line 10, in <module>
    from tacotron.synthesizer import Synthesizer
  File "/mnt/Tacotron-2/tacotron/synthesizer.py", line 12, in <module>
    from tacotron.models import create_model
  File "/mnt/Tacotron-2/tacotron/models/__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "/mnt/Tacotron-2/tacotron/models/tacotron.py", line 194
    log('  Tacotron Parameters       {:.3f} Million.'.format(np.sum([np.prod(v.get_shape().as_list()) for v in self.all_vars]) / 1_000_000))
                                                                                                                                         ^
SyntaxError: invalid syntax

any help would be appreciated!

Thanks!!!

**Comment by luuksuijkerbuijk** [comment]
I got the same problem.
Did you find a solution?

**Comment by tdplaza** [comment]
I do not use new version of Tacotron, but I think he is try to devide np.sum() by 1000000. but he wrote 1000000 as 1_000_000. Change this to number format, or just delete that line.

**Comment by luuksuijkerbuijk** [comment]
Thanks, easy as that! After deleting it in the Tacotron model you have to do the same for the Wavenet model
