### ISSUE TITLE
question about tensorflow version

### ISSUE THREAD

**Issue by ij00** [Rayhane-mamah/Tacotron-2#253]
I have tried to train LJSpeech-1.1 as 'python3 train.py', but I have got an error like this. 
So, can you tell me which version of tensorflow you used?
I used tensorflow 1.3. 

------------------------------------------------------------------------------
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from wavenet_vocoder.train import wavenet_train
  File "/disk1/iljoo/repo/tacotron2_v1/wavenet_vocoder/train.py", line 16, in <module>
    from wavenet_vocoder.models import create_model
  File "/disk1/iljoo/repo/tacotron2_v1/wavenet_vocoder/models/__init__.py", line 1, in <module>
    from .wavenet import WaveNet
  File "/disk1/iljoo/repo/tacotron2_v1/wavenet_vocoder/models/wavenet.py", line 10, in <module>
    from .modules import (Conv1D1x1, ConvTranspose2D, ConvTranspose1D, DiscretizedMixtureLogisticLoss, Embedding, GaussianMaximumLikelihoodEstimation,
  File "/disk1/iljoo/repo/tacotron2_v1/wavenet_vocoder/models/modules.py", line 43, in <module>
    class WeightNorm(tf.keras.layers.Wrapper):
AttributeError: module 'tensorflow' has no attribute 'keras'
------------------------------------------------------------------------------

**Comment by gloriouskilka** [comment]
@ij00 Hello. This is due to old tensorflow installed. You can update tensorflow, just comment that line, or find replacement in your version of tensorflow using google

**Comment by n5-suzuki** [comment]
@ij00 This repository requires tensorflow 1.7 or higher.

**Comment by ij00** [comment]
@gloriouskilka , @n5-suzuki  Thank you for your advice. I will try it again after updating tensorflow.
