### ISSUE TITLE
run train.py meet error

### ISSUE THREAD

**Issue by sunnnnnnnny** [Rayhane-mamah/Tacotron-2#259]
python3.5 tensorflow 1.4.0
Loaded metadata for 13100 examples (23.23 hours)
Traceback (most recent call last):
  File "train.py", line 138, in <module>
    main()
  File "train.py", line 128, in main
    tacotron_train(args, log_dir, hparams)
  File "/home/zyq/Tacotron-2/tacotron/train.py", line 376, in tacotron_train
    return train(log_dir, args, hparams)
  File "/home/zyq/Tacotron-2/tacotron/train.py", line 156, in train
    model, stats = model_train_mode(args, feeder, hparams, global_step)
  File "/home/zyq/Tacotron-2/tacotron/train.py", line 87, in model_train_mode
    is_training=True, split_infos=feeder.split_infos)
  File "/home/zyq/Tacotron-2/tacotron/models/tacotron.py", line 120, in initialize
    zoneout=hp.tacotron_zoneout_rate, scope='encoder_LSTM'))
  File "/home/zyq/Tacotron-2/tacotron/models/modules.py", line 197, in __init__
    name='encoder_fw_LSTM')
  File "/home/zyq/Tacotron-2/tacotron/models/modules.py", line 99, in __init__
    self._cell = tf.nn.rnn_cell.LSTMCell(num_units, state_is_tuple=state_is_tuple, name=name)
TypeError: __init__() got an unexpected keyword argument 'name'

**Comment by Clouxie** [comment]
First of all , I think you should probably update your tf version. I had similiar issues even on tf == 1.5.0

**Comment by sunnnnnnnny** [comment]
@Clouxie Very embarrassing, I tried to find that the highest version of tf_gpu that cudnn can support is 1.4. Do you have other methods?
