### ISSUE TITLE
preprocess.py "ValueError: dataset value entered 'M-AILABS' does not belong to supported datasets"

### ISSUE THREAD

**Issue by kwibjo** [Rayhane-mamah/Tacotron-2#264]
Hi, I'm trying to train tacotron-2 using M-AILABS en_UK but when I run preprocess:
`python preprocess.py --dataset='M-AILABS' --language='en_UK' --voice='female' --reader='elizabeth_klett' --merge_books=True`
I get this error:
`initializing preprocessing..
Selecting data folders..
Traceback (most recent call last):
  File "preprocess.py", line 110, in <module>
    main()
  File "preprocess.py", line 106, in main
    run_preprocess(args, modified_hp)
  File "preprocess.py", line 80, in run_preprocess
    input_folders = norm_data(args)
  File "preprocess.py", line 42, in norm_data
    args.dataset, supported_datasets))
ValueError: dataset value entered 'M-AILABS' does not belong to supported datasets: ['LJSpeech-1.0', 'LJSpeech-1.1', 'M-AILABS']`
I've also tried with the LJS and that works fine but 'M-AILABS' does not and I can't find any other issue tickets with this error. The "en_UK" data folder is in the root and it's structure is this:
`Tacotron-2/en_UK/by_book/female/elizabeth_klett`
Did I make a mistake or is this a bug?

**Comment by kwibjo** [comment]
Running on Windows 10 Python 3.6.6

**Comment by Clouxie** [comment]
You should try to type it without '   '   , if it won't help u can edit default values in preprocess.py and then just run "python preprocess.py" without any parameters.

**Comment by kwibjo** [comment]
I think this is a windows bug because I've just tried copy-pasting the same command on mac and linux machines and both ran it without problem. Same folder, same dependencies, same python version, etc... 🤔
