### ISSUE TITLE
ask for help 

### ISSUE THREAD

**Issue by doctor-xiang** [Rayhane-mamah/Tacotron-2#289]
Starting Synthesis
  0%|                                                                                                                                                                        | 0/9 [00:00<?, ?it/s]Traceback (most recent call last):
  File "synthesize.py", line 100, in <module>
    main()
  File "synthesize.py", line 94, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 36, in synthesize
    wavenet_in_dir = tacotron_synthesize(args, hparams, taco_checkpoint, sentences)
  File "/home/guo/Tacotron-2/tacotron/synthesize.py", line 135, in tacotron_synthesize
    return run_eval(args, checkpoint_path, output_dir, hparams, sentences)
  File "/home/guo/Tacotron-2/tacotron/synthesize.py", line 67, in run_eval
    mel_filenames, speaker_ids = synth.synthesize(texts, basenames, eval_dir, log_dir, None)
  File "/home/guo/Tacotron-2/tacotron/synthesizer.py", line 147, in synthesize
    assert len(mels) == len(linears) == len(texts)
AssertionError

**Comment by sysuzyx** [comment]
I met this error when running `synthesize.py  --mode='eval'`
Modify line 142 in Tacotron-2/tacotron/synthesizer.py from `target_lengths = [9999]`
to `target_lengths = [9999] * hparams.tacotron_synthesis_batch_size`

When running `synthesize.py  --mode='synthesis'`, this error don't happen.

Hope to solve your question.

**Comment by doctor-xiang** [comment]
thanks@sysuzyx,i try it
