### ISSUE TITLE
Non type object is not iterable

### ISSUE THREAD

**Issue by sarwar-se** [Rayhane-mamah/Tacotron-2#318]
initializing preprocessing..
Selecting data folders..
Traceback (most recent call last):
  File "preprocess.py", line 110, in <module>
    main()
  File "preprocess.py", line 106, in main
    run_preprocess(args, modified_hp)
  File "preprocess.py", line 83, in run_preprocess
    preprocess(args, input_folders, output_folder, hparams)
  File "preprocess.py", line 17, in preprocess
    metadata = preprocessor.build_from_path(hparams, input_folders, mel_dir, linear_dir, wav_dir, args.n_jobs, tqdm=tqdm)
  File "/home/sarwar/Downloads/Tacotron-2/datasets/preprocessor.py", line 32, in build_from_path
    for input_dir in input_dirs:
TypeError: 'NoneType' object is not iterable

**Comment by rohan6366** [comment]
bump

**Comment by Shehan-Irteza-Pranto** [comment]
@sarwar71 did you resolve this problem?
