### ISSUE TITLE
synthesis.py Failed to load checkpoint at logs-Tacotron-2/wave_pretrained/

### ISSUE THREAD

**Issue by DonggeunYu** [Rayhane-mamah/Tacotron-2#325]
After learning Tacotron-2 up to 10000 steps, I tried text to speech.

How to train the wave_pretrained?
~~~
python synthesize.py
~~~

Error:
~~~
synthesized mel spectrograms at tacotron_output/eval
Synthesizing audio from mel-spectrograms.. (This may take a while)
Traceback (most recent call last):
  File "/home/modeep/Documents/GitHub/Text2Speech/wavenet_vocoder/synthesize.py", line 73, in wavenet_synthesize
    checkpoint_path = tf.train.get_checkpoint_state(checkpoint).model_checkpoint_path
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesize.py", line 101, in <module>
    main()
  File "synthesize.py", line 95, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 42, in synthesize
    wavenet_synthesize(args, hparams, wave_checkpoint)
  File "/home/modeep/Documents/GitHub/Text2Speech/wavenet_vocoder/synthesize.py", line 76, in wavenet_synthesize
    raise RuntimeError('Failed to load checkpoint at {}'.format(checkpoint))
RuntimeError: Failed to load checkpoint at logs-Tacotron-2/wave_pretrained/
~~~

**Comment by wan-wei** [comment]
Hi @Yudonggeun , if you only want to test the performance of your Tacotron-2 model (not together with WaveNet model, right?), you may run `python synthesize.py --model=Tacotron`. Furthermore, if you want to test your own sentences, you may run `python synthesize.py --mode=live`, and it will ignore WaveNet model when the mode is live. Hope that this information is useful to you :)

**Comment by Yudonggeun** [comment]
Thank you for you!!
I fixed it.

**Comment by DonggeunYu** [comment]
Thank you for you!!
I fixed it.

**Comment by YanwangDream** [comment]
> Thank you for you!! I fixed it.

Hello, how can I fix it? I'm also having this issue and it's been bothering me for a long time
