### ISSUE TITLE
preprocess.py will fail on TensorFlow 2.0 due to contrib deprecation

### ISSUE THREAD

**Issue by RoelVdP** [Rayhane-mamah/Tacotron-2#364]
FYI,
```
$ python3 preprocess.py

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
```

And indeed, I tried with TF 2.0 alpha and got
```
$ python3 preprocess.py
Traceback (most recent call last):
  File "preprocess.py", line 6, in <module>
    from hparams import hparams
  File "/home/user/Tacotron-2/hparams.py", line 5, in <module>
    hparams = tf.contrib.training.HParams(
AttributeError: module 'tensorflow' has no attribute 'contrib'
```

**Comment by RoelVdP** [comment]
There are also various other errors related to Tensorflow, not necessarily related to TF2;

```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
WARNING:tensorflow:From /home/user/Tacotron-2/tacotron/models/tacotron.py:64: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
WARNING:tensorflow:From /home/user/Tacotron-2/tacotron/models/modules.py:100: LSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
```
etc... full list can be see by running 
```
python3 preprocess.py
python3 train.py --model='Tacotron-2'
```
After installing the (current) Tensorflow 1.13

**Comment by begeekmyfriend** [comment]
Most TF projects have been run on version 1.0...

**Comment by RoelVdP** [comment]
@begeekmyfriend  Hmhm thanks. Just a ticket for-future-work/improvement then :)

**Comment by WardoPo** [comment]
I keep getting `Bus error` when trying to execute `preprocess.py`, I've tried running `python3 preprocess.py` to no effect.
Currently working with Tensorflow 2.1.0, I'm asking here instead of opening a new issue, just in case it happens to be a related issue.
