### ISSUE TITLE
Synthesize error Checkpoint

### ISSUE THREAD

**Issue by C5YS** [Rayhane-mamah/Tacotron-2#369]
When I run "synthesize.py" and place the command "--checkpoint" to execute another version with less "Steps" I have the following error:

`python synthesize.py --checkpoint ~/tts-2/Tacotron-2/logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt-25000`
Using TensorFlow backend.
Running End-to-End TTS Evaluation. Model: Tacotron-2
Synthesizing mel-spectrograms from text..
Traceback (most recent call last):
  File "/home/dex/tts-2/Tacotron-2/tacotron/synthesize.py", line 121, in tacotron_synthesize
    checkpoint_path = tf.train.get_checkpoint_state(checkpoint).model_checkpoint_path
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesize.py", line 100, in <module>
    main()
  File "synthesize.py", line 94, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 36, in synthesize
    wavenet_in_dir = tacotron_synthesize(args, hparams, taco_checkpoint, sentences)
  File "/home/dex/tts-2/Tacotron-2/tacotron/synthesize.py", line 124, in tacotron_synthesize
    raise RuntimeError('Failed to load checkpoint at {}'.format(checkpoint))
RuntimeError: Failed to load checkpoint at logs-Tacotron-2/taco_/home/dex/tts-2/Tacotron-2/logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt-25000

----------------------------------------------------------------------------------------------------------

`python synthesize.py --checkpoint tacotron_model.ckpt-25000`
Using TensorFlow backend.
Running End-to-End TTS Evaluation. Model: Tacotron-2
Synthesizing mel-spectrograms from text..
Traceback (most recent call last):
  File "/home/dex/tts-2/Tacotron-2/tacotron/synthesize.py", line 121, in tacotron_synthesize
    checkpoint_path = tf.train.get_checkpoint_state(checkpoint).model_checkpoint_path
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesize.py", line 100, in <module>
    main()
  File "synthesize.py", line 94, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 36, in synthesize
    wavenet_in_dir = tacotron_synthesize(args, hparams, taco_checkpoint, sentences)
  File "/home/dex/tts-2/Tacotron-2/tacotron/synthesize.py", line 124, in tacotron_synthesize
    raise RuntimeError('Failed to load checkpoint at {}'.format(checkpoint))
RuntimeError: Failed to load checkpoint at logs-Tacotron-2/taco_tacotron_model.ckpt-25000

----------------------------------------------------------------------------------------------------------
`python synthesize.py --checkpoint pretrained/tacotron_model.ckpt-25000`
Using TensorFlow backend.
Running End-to-End TTS Evaluation. Model: Tacotron-2
Synthesizing mel-spectrograms from text..
Traceback (most recent call last):
  File "/home/dex/tts-2/Tacotron-2/tacotron/synthesize.py", line 121, in tacotron_synthesize
    checkpoint_path = tf.train.get_checkpoint_state(checkpoint).model_checkpoint_path
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesize.py", line 100, in <module>
    main()
  File "synthesize.py", line 94, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 36, in synthesize
    wavenet_in_dir = tacotron_synthesize(args, hparams, taco_checkpoint, sentences)
  File "/home/dex/tts-2/Tacotron-2/tacotron/synthesize.py", line 124, in tacotron_synthesize
    raise RuntimeError('Failed to load checkpoint at {}'.format(checkpoint))
RuntimeError: Failed to load checkpoint at logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt-25000

----------------------------------------------------------------------------------------------------------
What am I doing wrong? Thank you.

**Comment by Thien223** [comment]
python could not find the checkpoint in given path. make sure the path is right, by creating simple code that can successfully load the checkpoint

**Comment by C5YS** [comment]
Could you guide me? The truth is that I do not know where to start.

I enter the full path and I generate an error, but when I do not enter "--checkpoint" the last trained model runs without problems.

**Comment by VictorGRP** [comment]
Even though it is not the best idea, you could try to hardcode the path into the code and check if it works that way

**Comment by giacaglia** [comment]
You need to run it on tensorflow-10 and cuda 9.0
