### ISSUE TITLE
callback pyfunc_0 is not found when deploy tacotron model

### ISSUE THREAD

**Issue by superhg2012** [Rayhane-mamah/Tacotron-2#405]
Hi, when deploying tacotron pb model, an tf error occured as below

Traceback (most recent call last):
  File "/opt/anaconda3-5.1.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/opt/anaconda3-5.1.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/anaconda3-5.1.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: callback pyfunc_0 is not found
Traceback (most recent call last):

  File "/opt/anaconda3-5.1.0/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 195, in __call__
    raise ValueError("callback %s is not found" % token)

ValueError: callback pyfunc_0 is not found

	 [[{{node Tacotron_model/PyFunc}} = PyFunc[Tin=[DT_INT32, DT_INT32], Tout=[DT_INT32], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_inputs_0_1, Tacotron_model/strided_slice)]]
	 [[{{node griffinlim/inverse_stft_19/overlap_and_add/frame/GatherV2/_543}} = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_7394_griffinlim/inverse_stft_19/overlap_and_add/frame/GatherV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

anybody who met this error too? how did you fix it?

**Comment by lyv023** [comment]
Dear, my friend. Do you fix this problem? I 've met the same proble and stucked me for a while. Thanks for helping me.
