### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1,2049) (0,) 

### ISSUE THREAD

**Issue by lzj520** [Rayhane-mamah/Tacotron-2#427]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 111, in <module>
    main()
  File "preprocess.py", line 107, in main
    run_preprocess(args, modified_hp)
  File "preprocess.py", line 84, in run_preprocess
    preprocess(args, input_folders, output_folder, hparams)
  File "preprocess.py", line 15, in preprocess
    metadata = preprocessor.build_from_path(hparams, input_folders, wav_dir, mel_dir, args.n_jobs, tqdm=tqdm)
  File "/home/lzj/Tacotron-2-mandarin-mel-prediction/datasets/preprocessor.py", line 51, in build_from_path
    return [future.result() for future in tqdm(futures) if future.result() is not None]
  File "/home/lzj/Tacotron-2-mandarin-mel-prediction/datasets/preprocessor.py", line 51, in <listcomp>
    return [future.result() for future in tqdm(futures) if future.result() is not None]
  File "/usr/local/python3/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/python3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (1,2049) (0,)

**Comment by toooooodo** [comment]
check numpy version and scipy version, make sure they are same as requirements

**Comment by senisioi** [comment]
try `pip3 install numpy==1.16.0` the requirements.txt seems to have conflicting entries when installing the latest tensorflow 1
