### ISSUE TITLE
RuntimeError: Failed to load checkpoint at logs-Tacotron-2\taco_pretrained/

### ISSUE THREAD

**Issue by CrazyPlaysHD** [Rayhane-mamah/Tacotron-2#507]
Traceback (most recent call last):
  File "synthesize.py", line 101, in <module>
    main()
  File "synthesize.py", line 95, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 37, in synthesize
    wavenet_in_dir = tacotron_synthesize(args, hparams, taco_checkpoint, sentences)
  File "C:\Users\Superuser\Desktop\Tacotron-2-master\tacotron\synthesize.py", line 124, in tacotron_synthesize
    raise RuntimeError('Failed to load checkpoint at {}'.format(checkpoint))
RuntimeError: Failed to load checkpoint at logs-Tacotron-2\taco_pretrained/

**Comment by YanwangDream** [comment]
Hello, is it solved? I'm running into this issue as well
