### ISSUE TITLE
Loss exploded to nan after ctrl+C to stop and start again

### ISSUE THREAD

**Issue by butterl** [Rayhane-mamah/Tacotron-2#60]
Hi ,  I  use Ctrl+C to cancel the Tacotron train to release GPU for other work then after I start the Tacotron again， the  Loss exploded to nan for all the exsiting checkpoint， but will be OK when I remove all checkpoint and start from begining， any instruction on due with this ?

```
Loading checkpoint logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt-67500

Generated 32 test batches of size 48 in 4.530 sec

Generated 32 train batches of size 48 in 4.558 sec
Loss exploded to nan at step 67501=nan, avg_loss=nan]
Exiting due to exception: Loss exploded
Traceback (most recent call last):
  File "/home/butter/Audio/CHS/Tacotron-2-master-CHS/tacotron/train.py", line 181, in train
    raise Exception('Loss exploded')
Exception: Loss exploded
Exception in thread background:
Traceback (most recent call last):
  File "/home/butter/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/home/butter/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/home/butter/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/eval_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](datafeeder/eval_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/mel_targets_0_3, _arg_datafeeder/token_targets_0_5, _arg_datafeeder/linear_targets_0_2, _arg_datafeeder/targets_lengths_0_4)]]

```

**Comment by butterl** [comment]
Tried many ways and a sudden power loss reboot solved it  and do not reproduced :(
