### ISSUE TITLE
preprocess.py running error, any package dependence needed？ 

### ISSUE THREAD

**Issue by butterl** [Rayhane-mamah/Tacotron-2#9]
I tried added path for solving not finding package in models on my ubuntu 16.04 machine
```
import argparse
++ import sys
++ sys.path.append("./models")
from tacotron.preprocess import tacotron_preprocess
from multiprocessing import cpu_count
```
and removing tacotron from tacotron.xxx import xxx to avoid error like below
```
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from tacotron.datasets.feeder import Feeder
ImportError: No module named 'tacotron'
```

but still get error like below：
```
tacotron$ python3 preprocess.py
Traceback (most recent call last):
  File "preprocess.py", line 5, in <module>
    from tacotron.preprocess import tacotron_preprocess
ImportError: No module named 'tacotron.preprocess'; 'tacotron' is not a package
```

I grep the project ，only find tacotron_preprocess be used in  preprocess.py and not defined, is there any other package I need to install other than the requirements.txt?

Thanks

**Comment by Rayhane-mamah** [comment]
Hello @butterl thanks for reaching out!

Actually thank you very much for reporting this, I just noticed that the files upload bugged for "tacotron/preprocess.py". If you could just give me 1 hour max I'll be uploading the correct preprocessing (for Tacotron + Wavenet).

Other than that, if you're correctly under **Tacotron-2** folder (e.g: cd path/to/project/Tacotron-2/ ) then all importations should work correctly. What you can do is try adding the main **Tacotron-2** folder to the path?

Sorry for the rushed answer, hopefully in the next commit (1hour max) it will be fixed!
Thank you for your patience.

**Comment by Rayhane-mamah** [comment]
There you go (6236a6b33234c99f3648f4c583ccfe58402cc96d) @butterl 

Try under this commit and tell me how it goes.

**Comment by butterl** [comment]
Thanks Rayhane， the preproess.py is OK now，and I meet an TF error when running train.py, I'm not sure if the TF version that make  the error. TF version I use is as below:

```
butter@ubuntu16.04:~/code/ML/Tacotron-2$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.5.0'
>>> tf.__path__
['/usr/local/lib/python3.5/dist-packages/tensorflow']
```

And the Error log is as below
```
butter@ubuntu16.04:~/code/ML/Tacotron-2$ python3 train.py --model='Tacotron'
Checkpoint path: logs-Tacotron/pretrained/model.ckpt
Loading training data from: training_data/train.txt
Using model: Tacotron
Hyperparameters:
  allow_clipping_in_normalization: True
  attention_dim: 128
  attention_filters: 32
  attention_kernel: (31,)
  cleaners: english_cleaners
  decoder_layers: 2
  decoder_lstm_units: 1024
  embedding_dim: 512
  enc_conv_channels: 512
  enc_conv_kernel_size: (5,)
  enc_conv_num_layers: 3
  encoder_lstm_units: 256
  fft_size: 1024
  fmax: 7600
  fmin: 125
  frame_shift_ms: None
  griffin_lim_iters: 60
  hop_size: 256
  impute_finished: False
  input_type: mulaw-quantize
  log_scale_min: -32.23619130191664
  mask_encoder: False
  mask_finished: False
  max_abs_value: 4.0
  max_iters: 1000
  mel_normalization: True
  min_level_db: -100
  num_mels: 80
  outputs_per_step: 5
  postnet_channels: 512
  postnet_kernel_size: (5,)
  postnet_num_layers: 5
  power: 1.55
  prenet_layers: [256, 256]
  quantize_channels: 256
  ref_level_db: 20
  rescale: True
  rescaling_max: 0.999
  sample_rate: 22050
  silence_threshold: 2
  smoothing: False
  stop_at_any: True
  symmetric_mels: True
  tacotron_adam_beta1: 0.9
  tacotron_adam_beta2: 0.999
  tacotron_adam_epsilon: 1e-06
  tacotron_batch_size: 32
  tacotron_decay_learning_rate: True
  tacotron_decay_rate: 0.4
  tacotron_decay_steps: 50000
  tacotron_dropout_rate: 0.5
  tacotron_final_learning_rate: 1e-05
  tacotron_initial_learning_rate: 0.001
  tacotron_reg_weight: 1e-06
  tacotron_teacher_forcing_ratio: 1.0
  tacotron_zoneout_rate: 0.1
  trim_silence: True
Loaded metadata for 13100 examples (23.94 hours)
no step_counter file found, assuming there is no saved checkpoint
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    main()
  File "train.py", line 26, in main
    tacotron_train(args)
  File "/home/butter/code/ML/Tacotron-2/tacotron/train.py", line 174, in tacotron_train
    train(log_dir, args)
  File "/home/butter/code/ML/Tacotron-2/tacotron/train.py", line 69, in train
    model.initialize(feeder.inputs, feeder.input_lengths, feeder.mel_targets, feeder.token_targets)
  File "/home/butter/code/ML/Tacotron-2/tacotron/models/tacotron.py", line 106, in initialize
    maximum_iterations=max_iters)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 309, in dynamic_decode
    swap_memory=swap_memory)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2934, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2720, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2662, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 254, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/butter/code/ML/Tacotron-2/tacotron/models/custom_decoder.py", line 123, in step
    (cell_outputs, stop_token), cell_state = self._cell(inputs, state)
  File "/home/butter/code/ML/Tacotron-2/tacotron/models/Architecture_wrappers.py", line 194, in __call__
    attention_layer=None)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1000, in _compute_attention
    cell_output, previous_alignments=previous_alignments)
**TypeError: __call__() got an unexpected keyword argument 'previous_alignments'**
```

**Comment by butterl** [comment]
Tried updated to TF1.6 and  the train.py start to run， think tensorflow==1.6  need to be added to requirements.txt for some one miss the TF version warning in the Readme.md as me :)
