### ISSUE TITLE
Installing LWS

### ISSUE THREAD

**Issue by Jeff-Winchell** [Rayhane-mamah/Tacotron-2#90]
I apparently magically had whatever form of Visual C++ on my machine (I did it following VERY explicit rules in installing the CUDA driver for TensorFlow).

I just got a Deep Learning Virtual Machine on Azure thinking it already had this. Apparently not. So I downloaded Visual Studio 17 Community Edition and then tried to install lws and got this dump:

python -m pip install lws
Collecting lws
  Using cached https://files.pythonhosted.org/packages/3a/c7/856af2e1202e7a4c5102406196aa661edb402256e7ce2334be0c0d8afa2e/lws-1.2.tar.gz
Building wheels for collected packages: lws
  Running setup.py bdist_wheel for lws ... error
  Complete output from command C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JEFFWI~1\\AppData\\Local\\Temp\\2\\pip-build-ffi6jxkf\\lws\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\JEFFWI~1\AppData\Local\Temp\2\tmpbnuukb6xpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\JEFFWI~1\AppData\Local\Temp\2\pip-build-ffi6jxkf\lws\setup.py", line 55, in <module>
      "Programming Language :: Python :: 3.6",
    File "C:\Anaconda\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "C:\Anaconda\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Anaconda\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Anaconda\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Anaconda\lib\site-packages\wheel\bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "C:\Anaconda\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Anaconda\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Anaconda\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Anaconda\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Anaconda\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Anaconda\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
      _build_ext.run(self)
    File "C:\Anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "C:\Anaconda\lib\distutils\command\build_ext.py", line 308, in run
      force=self.force)
    File "C:\Anaconda\lib\distutils\ccompiler.py", line 1031, in new_compiler
      return klass(None, dry_run, force)
    File "C:\Anaconda\lib\distutils\cygwinccompiler.py", line 285, in __init__
      CygwinCCompiler.__init__ (self, verbose, dry_run, force)
    File "C:\Anaconda\lib\distutils\cygwinccompiler.py", line 129, in __init__
      if self.ld_version >= "2.10.90":
  TypeError: '>=' not supported between instances of 'NoneType' and 'str'

  ----------------------------------------
  Failed building wheel for lws
  Running setup.py clean for lws
Failed to build lws
Installing collected packages: lws
  Running setup.py install for lws ... error
    Complete output from command C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JEFFWI~1\\AppData\\Local\\Temp\\2\\pip-build-ffi6jxkf\\lws\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JEFFWI~1\AppData\Local\Temp\2\pip-6iw6myov-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JEFFWI~1\AppData\Local\Temp\2\pip-build-ffi6jxkf\lws\setup.py", line 55, in <module>
        "Programming Language :: Python :: 3.6",
      File "C:\Anaconda\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\Anaconda\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Anaconda\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Anaconda\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Anaconda\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Anaconda\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
        _build_ext.run(self)
      File "C:\Anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\Anaconda\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "C:\Anaconda\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Anaconda\lib\distutils\cygwinccompiler.py", line 285, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "C:\Anaconda\lib\distutils\cygwinccompiler.py", line 129, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'

    ----------------------------------------
Command "C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JEFFWI~1\\AppData\\Local\\Temp\\2\\pip-build-ffi6jxkf\\lws\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JEFFWI~1\AppData\Local\Temp\2\pip-6iw6myov-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\JEFFWI~1\AppData\Local\Temp\2\pip-build-ffi6jxkf\lws\

What a !@#!@$ mess. Anyone got any clues?
In the meantime I will shut down my $10/hr VM until I figure out how to get lws installed.

I need lws, as far as I know because of the preproccess.py program. If it's only reason for lws I may find a way to rapidly download all the files I already preprocessed on my local machine (uploading from my machine wasn't an option since the VM told me it would take a day of running at $10/hr to do that).

**Comment by zhangyizhong17** [comment]
I m not sure whether i m answering your question.
It seems windows doesn't support lws.
I failed installing lws on my windows as well, but lws can be easily installed on my llinux.

**Comment by Jeff-Winchell** [comment]
I got lws on my Windows laptop. I haven't yet figured out what is different that matters on the Windows VM I have on Azure. But I changed use_AWS to False in hparams.py and was able to run preprocess.py and train.py --model=Tacotron-2.

**Comment by Jeff-Winchell** [comment]
Also, I don't use Linux, so how anything works on that is not relevent to me.

**Comment by Rayhane-mamah** [comment]
Hey @Jeff-Winchell I am hoping you solved the issue in the meantime :)

If not, no problem, don't use lws haha.. We only use it when porting to r9y9's wavenet anyway. Closing the issue, feel free to reopen if you only want to make me mad :)
