### ISSUE TITLE
got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by fazlekarim** [Rayhane-mamah/Tacotron-2#91]
I am getting the following error when running train.py

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification/train.py", line 134, in <module>
    main()
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification/train.py", line 128, in main
    train(args, log_dir, hparams)
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification/train.py", line 54, in train
    checkpoint = tacotron_train(args, log_dir, hparams)
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification\tacotron\train.py", line 305, in tacotron_train
    return train(log_dir, args, hparams)
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification\tacotron\train.py", line 127, in train
    model, stats = model_train_mode(args, feeder, hparams, global_step)
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification\tacotron\train.py", line 69, in model_train_mode
    is_training=True)
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification\tacotron\models\tacotron.py", line 64, in initialize
    zoneout=hp.tacotron_zoneout_rate, scope='encoder_LSTM'))
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification\tacotron\models\modules.py", line 139, in __init__
    name='encoder_fw_LSTM')
  File "C:/Users/fakarim/PycharmProjects/Speaker_Verification\tacotron\models\modules.py", line 39, in __init__
    self._cell = tf.nn.rnn_cell.LSTMCell(num_units, state_is_tuple=state_is_tuple, name=name)
TypeError: __init__() got an unexpected keyword argument 'name'

**Comment by fazlekarim** [comment]
wrong tensorflow version. thats why.

**Comment by NewEricWang** [comment]
@fazlekarim , I also meet same problem.Could you tell me how do resolved the problem?  Thanks!
