### ISSUE TITLE
Incorrect parsing of hparams

### ISSUE THREAD

**Issue by gvashkevich** [Rayhane-mamah/Tacotron-2#93]
Hello!

When I try to start the training and personalize the `tacotron_test_size` hyperparameter like this: `python3 train.py --model='Tacotron' --hparams='tacotron_test_size=20'` I get the following error from tensorflow:

```
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    main()
  File "train.py", line 114, in main
    log_dir, hparams = prepare_run(args)
  File "train.py", line 34, in prepare_run
    modified_hp = hparams.parse(args.hparams)
  File "/usr/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/hparam.py", line 525, in parse
    values_map = parse_values(values, type_map)
  File "/usr/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/hparam.py", line 280, in parse_values
    results_dictionary)
  File "/usr/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/hparam.py", line 83, in _process_scalar_value
    parsed_value = parse_fn(m_dict['val'])
TypeError: NoneType takes no arguments
```

The possible solution: set  `tacotron_test_size = -1`  in `Tacotron-2\hparams.py` and replace
```
test_size = (hparams.tacotron_test_size if hparams.tacotron_test_size is not None
			else hparams.tacotron_test_batches * hparams.tacotron_batch_size)
``` 
with 
```
test_size = (hparams.tacotron_test_size if hparams.tacotron_test_size != -1
			else hparams.tacotron_test_batches * hparams.tacotron_batch_size)
```
in `Tacotron-2\tacotron\feeder.py`

**Comment by Rayhane-mamah** [comment]
Hello @gvashkevich good point, it can be a solution indeed. I am however leaving it as it is now and I recommend making major changes like this one directly on the hparams.py file. the parsing option is mainly used for other model training options like modification of learning rate decay steps, batch size of some other training related parameters.

Still thanks for your contribution :)
